spring:
  datasource:
    url: ${DB_PATH}?rewriteBatchedStatements=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
    properties:
      hibernate:
        format_sql: false
        show_sql: false
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379

oauth2:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    response-type: code
    grant-type: authorization_code
    authorization-uri: https://kauth.kakao.com/oauth/authorize
    redirect-uri: ${SERVER_URL}/api/oauth/login/kakao
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me

  naver:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}
    response-type: code
    grant-type: authorization_code
    state: ${NAVER_STATE}
    authorization-uri: https://nid.naver.com/oauth2.0/authorize
    redirect-uri: ${SERVER_URL}/api/oauth/login/naver
    token-uri: https://nid.naver.com/oauth2.0/token
    user-info-uri: https://openapi.naver.com/v1/nid/me

jwt:
  secret-key: ${JWT_SECRET}

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    url: /docs/open-api-3.0.1.json
    path: /docs

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

appKey: ${TMAP_APP_KEY}
confirmKey: ${JUSO_API_KEY}